import { format } from '../parser/externalLinks'

/**
 * Renders <external-link kind="..." id="..."/> elements generated by the core
 * parser as <a/> tags.
 */
export class ExternalLink extends HTMLElement {
  constructor() {
    super()
    const kind = this.getAttribute('kind')
    const id = this.getAttribute('id')

    const result = kind && id && format({ kind, id })
    if (result) {
      const { href, label } = result
      this.attachShadow({ mode: 'open' }).innerHTML = `<a href="${href}">${label}</a>`
    }
  }
}
