name: core

on:
  push:
    paths:
      - packages/core/**
      - .github/workflows/core.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install packages
        run: npm install
      - name: Bootstrap repo
        run: npx lerna bootstrap
      - name: Run tests
        run: |-
          cd packages/core
          npm run test
