name: Lint
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install packages
        run: npm install
      - name: Check formatting
        run: npm run fmt:check
